name: optuae
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: any
  dropdown_button2: ^1.9.2
  image_picker: ^0.8.6+1
  google_fonts: any
  buttons_tabbar: ^1.3.6
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  flutter_spinkit: ^5.1.0
  flutter_html: ^2.2.1
  cached_network_image: ^3.2.3
  windows1251: ^1.0.2
  http: ^0.13.4
  path_provider: ^2.0.14
  csv: ^5.0.2
  dropdown_search: ^2.0.1
  onesignal_flutter: ^3.5.1
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


